apiVersion: v1
kind: Namespace
metadata:
  name:  api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: api-container
        image: ttl.sh/telepresence-demo-user-svc:2h
        imagePullPolicy: Always
        ports:
        - name:  api
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name:  user-svc
  namespace: api
spec:
  selector:
    app:  user-svc
  type:  ClusterIP
  ports:
  - name: api
    port:  80
    targetPort:  8080